### ISSUE TITLE
How to download an ebook file?

### ISSUE THREAD

**Issue by ghost** [JoshuaRLi/pylibgen#10]
I can't get how to download the actual ebook file.

Let's say I get this URL:

```
>>> print(url)
'http://libgen.io/ads.php?md5=EC804A6C38F7415F5F612AC0902C2B26'
```

I've tried all these methods:

```py
from pylibgen import Library
lib = Library()

###

r = requests.get(url)

###

with open('my_ebook','wb') as f:
    for chunk in r.iter_content(chunk_size=128):
        f.write(chunk)

###

lib.download(info['md5'], data_folder) #this method doesn't exist

###

os.system('wget http://libgen.io/ads.php?md5=EC804A6C38F7415F5F612AC0902C2B26')

###

r = requests.head(url, allow_redirects=True, timeout=3)
r.raise_for_status()
```

And maybe some others that I don't recall.

I still don't get the ebook file downloaded :man_shrugging:.

**Comment by joshuarli** [comment]
From the readme:

```
Book.get_url(filehost='...') will return the standard filehost gateway url.

There is no functionality to bypass any intermediate advertisement pages, ...
```

You'll have to click on the "GET" link (for libgen.io) to start the actual download.

**Comment by ghost** [comment]
I see. I was trying to automate the whole process, including getting the file.

**Comment by joshuarli** [comment]
You can use pylibgen to get the URL, then download the page and parse through it to extract the link. As noted in the readme, I've deliberately left this functionality out.

**Comment by ghost** [comment]
I will try that then, thank you very much :blush:
