### ISSUE TITLE
I just wonder

### ISSUE THREAD

**Issue by ZedYeung** [JoshuaRLi/pylibgen#2]
How did you find 'http://{}/json.php?ids={}&fields={}'

**Comment by joshuarli** [comment]
Hey! Sorry for the overdue reply. If I remember correctly, I was googling around randomly and stumbled upon [this](http://garbage.world/posts/libgen/). It's almost 3 years old, but apparently the endpoint is still there.

**Comment by ZedYeung** [comment]
That‘s pretty cool. Thank you very much.
