### ISSUE TITLE
KeyError when only one book found

### ISSUE THREAD

**Issue by karlic** [JoshuaRLi/pylibgen#7]
If the search returns only one book, a key error is returned.

```
>>> ids = lg.search('Mushrooms and Toadstools of Britain and Europe', 'title')
>>> ids
['1819507']
>>> books = lg.lookup(ids)
>>> from pprint import pprint; pprint(books[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 0
>>> 

```

**Comment by joshuarli** [comment]
That's because if only one id is specified, then a Book object will be returned and it won't be contained in a list. I might be separating into `lookup` and something like `batch_lookup` to make this more clear, before 2.0.0 is officially released.

**Comment by joshuarli** [comment]
In 2.0.0, I ended up changing `Library.lookup` to yield `Book` objects instead, to keep the API clean.
